services:

  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ./prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:11.0.0
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor traceQLStreaming metricsSummary
    ports:
      - "3000:3000"
  
  web:
    build: .
    container_name: web
    command: opentelemetry-instrument flask run -p 8080 --host=0.0.0.0
    volumes:
      - ./source:/app
    ports:
      - "8080:8080"
    environment:
      - OTEL_SERVICE_NAME=WEB
      - OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED=true

      - OTEL_TRACES_EXPORTER=none
      - OTEL_METRICS_EXPORTER=console,otlp
      - OTEL_LOG_EXPORTER=console
      
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317

  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector:latest
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "8888:8888"
      - "8889:8889"
    command: ["--config=/etc/otel-collector-config.yaml"]
    depends_on:
      - prometheus

volumes:
  mimir-data:
    driver: local