{
 "title": "Opentelemetry",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "200 Requests",
   "type": "stat",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "otel_http_server_duration_milliseconds_count{exported_job=\"WEB\", http_status_code=\"200\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "404 Requests",
   "type": "stat",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "otel_http_server_duration_milliseconds_count{exported_job=\"WEB\", http_status_code=\"404\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "500 Requests",
   "type": "stat",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "otel_http_server_duration_milliseconds_count{exported_job=\"WEB\", http_status_code=\"500\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}